// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiFGajml4-zu_HxGDP1gHg3H6la1imK1A',
    appId: '1:100243021797:web:5e28d9da511180d7e2190c',
    messagingSenderId: '100243021797',
    projectId: 'alfalah-51d64',
    authDomain: 'alfalah-51d64.firebaseapp.com',
    storageBucket: 'alfalah-51d64.firebasestorage.app',
    measurementId: 'G-XHN8119CFB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW4X2GQ913hm94BtSjy8vfqkoHrwvE6_M',
    appId: '1:100243021797:android:c7a93b6a3a718465e2190c',
    messagingSenderId: '100243021797',
    projectId: 'alfalah-51d64',
    storageBucket: 'alfalah-51d64.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP7COgIPgRylZnPZrTBk8zbdHd__g_1mk',
    appId: '1:100243021797:ios:0a1d8ba94e6898f8e2190c',
    messagingSenderId: '100243021797',
    projectId: 'alfalah-51d64',
    storageBucket: 'alfalah-51d64.firebasestorage.app',
    iosBundleId: 'com.example.funfix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDP7COgIPgRylZnPZrTBk8zbdHd__g_1mk',
    appId: '1:100243021797:ios:0a1d8ba94e6898f8e2190c',
    messagingSenderId: '100243021797',
    projectId: 'alfalah-51d64',
    storageBucket: 'alfalah-51d64.firebasestorage.app',
    iosBundleId: 'com.example.funfix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiFGajml4-zu_HxGDP1gHg3H6la1imK1A',
    appId: '1:100243021797:web:489e6c977ed73d38e2190c',
    messagingSenderId: '100243021797',
    projectId: 'alfalah-51d64',
    authDomain: 'alfalah-51d64.firebaseapp.com',
    storageBucket: 'alfalah-51d64.firebasestorage.app',
    measurementId: 'G-PLR8QCMF4G',
  );
}
